# Generated by Django 4.1.7 on 2023-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('agency_name', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
                ('close_date', models.DateField()),
            ],
        ),
    ]
