# Generated by Django 4.1.7 on 2023-03-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_opportunity_agency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
