# Generated by Django 4.1.7 on 2023-03-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_opportunity_agency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='post_date',
        ),
    ]
