# Generated by Django 4.1.7 on 2023-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_opportunity_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='addl_info_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='addl_info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='agency_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='archive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='award_ceiling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='award_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='category_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='close_date_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_description',
            field=models.CharField(blank=True, max_length=102, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cost_sharing_or_match_req',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligibility_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='est_total_funding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='exp_num_awards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='external_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='grant_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opp_category_explanation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
