# Generated by Django 4.1.7 on 2023-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_opportunity_grant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='grant_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
