# Generated by Django 4.1.7 on 2023-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_opportunity_grant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='award_ceiling',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='award_floor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='est_total_funding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
