insert into search_opportunity (
    grant_id,
    title,
    external_id,
    category,
    opp_category_explanation,
    category_explanation,
    eligibility_info,
    agency_code,
    agency_name,
    post_date,
    close_date,
    close_date_explanation,
    last_updated_date,
    award_ceiling,
    award_floor,
    est_total_funding,
    exp_num_awards,
    description,
    version,
    cost_sharing_or_match_req,
    archive_date,
    addl_info_url,
    addl_info_text,
    contact_email,
    contact_description,
    contact_text
  )
select
    json_extract(value, '$.OpportunityID'),
    json_extract(value, '$.OpportunityTitle'),
    json_extract(value, '$.OpportunityNumber'),
    json_extract(value, '$.OpportunityCategory'),
    json_extract(value, '$.OpportunityCategoryExplanation'),
    -- FundingInstrumentType              []string
    -- CategoryOfFundingActivity          []string
    json_extract(value, '$.CategoryExplanation'),
    -- CFDANumbers                        []string
    -- EligibleApplicants                 []string
    json_extract(value, '$.AdditionalInformationOnEligibility'),
    json_extract(value, '$.AgencyCode'),
    json_extract(value, '$.AgencyName'),
    json_extract(value, '$.PostDate'),
    json_extract(value, '$.CloseDate'),
    json_extract(value, '$.CloseDateExplanation'),
    json_extract(value, '$.LastUpdatedDate'),
    json_extract(value, '$.AwardCeiling'),
    json_extract(value, '$.AwardFloor'),
    json_extract(value, '$.EstimatedTotalProgramFunding'),
    json_extract(value, '$.ExpectedNumberOfAwards'),
    json_extract(value, '$.Description'),
    json_extract(value, '$.Version'),
    json_extract(value, '$.CostSharingOrMatchingRequirement'),
    json_extract(value, '$.ArchiveDate'),
    json_extract(value, '$.AdditionalInformationURL'),
    json_extract(value, '$.AdditionalInformationText'),
    json_extract(value, '$.GrantorContactEmail'),
    json_extract(value, '$.GrantorContactEmailDescription'),
    json_extract(value, '$.GrantorContactText')
from json_each(json_extract(readfile('output.json'), '$.OpportunitySynopsisDetail'));
